name: flutter_erfan_youtube_muxer_2025
description: Flutter package for YouTube video downloading and muxing with quality selection.
version: 1.0.1
homepage: https://github.com/erfanalizada/Flutter_erfan_youtube_muxer_2025
repository: https://github.com/erfanalizada/Flutter_erfan_youtube_muxer_2025
issue_tracker: https://github.com/erfanalizada/Flutter_erfan_youtube_muxer_2025/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"
  
dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.4.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  video_player: ^2.9.5
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
